name: Build packages PR

on:
  pull_request:
    paths:
      - 'packages/**'
      - 'packages.sh'
      - '.github/workflows/build-packages.yaml'

concurrency:
  group: pr-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  lx06:
    name: LX06
    if: ${{ github.repository == 'danielk117/xiaoai-patch' }}
    uses: danielk117/xiaoai-patch/.github/workflows/build-packages.yaml@master
    with:
      model: LX06
